version: '3'

services:
  relay:
    image: sergeyitsib/hyper-dex-swap-node:latest
    container_name: hyper-dex-swap-node
    restart: always
    env_file:
      - ./.env
    environment:
      PORT: '3201'
      CORS_ORIGIN: '*'
    ports:
      - '3201:3201'
